### ISSUE TITLE
Error resolving ImageStreamTag nodejs:8 in namespace openshift: unable to find latest tagged image

### ISSUE THREAD

**Issue by shawndwells** [SecurityCentral/openshift-templates#1]
![image](https://user-images.githubusercontent.com/5713754/37748174-3eae288e-2d59-11e8-8ac1-58e8be0a1e5b.png)

**Comment by shawndwells** [comment]
Was able to get the template to deploy by using nodejs:latest

old:
`````
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: nodejs:8
          namespace: openshift
`````

new:
`````
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: nodejs:latest
          namespace: openshift
`````

However, while it deploys, a new message is shown when accessing the deployment:
![image](https://user-images.githubusercontent.com/5713754/37748730-5547550a-2d5b-11e8-9c2b-65ea7298f8e5.png)
